# Generated by Django 4.2.3 on 2023-08-13 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaprod',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
    ]
